export const cakes = [
  {
    slug: 'tiramisu-cake',
    bestSeller: true,
    name: 'Tiramisu Cake',
    detail: 'Espresso-soaked sponge and ladyfingers, layered into a soft cream cake and dusted with fine cocoa powder',
    price: 'from $120',
    image: '/images/gallery-4.jpg',
    photoCaption: 'Cake in photo shown is an 8" round',
    sizes: [
      { label: '6"', price: '$120' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Chocolate'],
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
    ],
  },
  {
    slug: 'matchamisu',
    bestSeller: true,
    name: 'Matchamisu',
    detail: 'Nami matcha-soaked ladyfingers, layered into a soft cream cake and dusted with Nami matcha, topped with fresh strawberries',
    price: 'from $120',
    image: '/images/cake-matchamisu.png',
    photoCaption: 'Cake in photo shown is an 8" round',
    sizes: [
      { label: '6"', price: '$120' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Nami Matcha', 'Vanilla'],
    shapes: ['Round', 'Heart'],
    fillings: [],
  },
  {
    slug: 'soft-chocolate',
    name: 'Chocolate Baby',
    detail: 'Layered chocolate sponge with soft cream, cocoa dusting, topped with Hershey\'s chocolate',
    price: 'from $105',
    image: '/images/cake-soft-chocolate.jpg',
    photoCaption: 'Cake in photo shown is an 8" round',
    sizes: [
      { label: '6"', price: '$105' },
      { label: '8"', price: '$115' },
    ],
    flavors: ['Chocolate'],
    shapes: ['Round', 'Heart'],
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'raspberry-baby',
    bestSeller: true,
    bestSellerLast: true,
    name: 'Raspberry Baby',
    detail: 'Soft cream cake topped with a border of piped cream and fresh raspberries',
    price: 'from $125',
    image: '/images/cake-raspberry-baby-chocolate.jpg',
    images: [
      '/images/cake-raspberry-baby-chocolate.jpg',
      '/images/cake-raspberry-baby.jpg',
      '/images/cake-raspberry-baby-alt.jpg',
    ],
    photoCaption: 'Cake in photo shown is a 6" round',
    sizes: [
      { label: '6"', price: '$125' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round', 'Heart'],
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'strawberry-matcha',
    bestSeller: true,
    name: 'Strawberry Matcha',
    detail: 'Soft cream cake dusted with Nami matcha and fresh strawberries',
    price: 'from $120',
    image: '/images/cake-strawberry-matcha.jpg',
    photoCaption: 'Cake in photo shown is a 6" heart',
    sizes: [
      { label: '6"', price: '$120' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Vanilla', 'Matcha (+$10)'],
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
    ],
  },
  {
    slug: 'strawberry-fields',
    bestSeller: true,
    name: 'Strawberry Fields',
    detail: 'Soft cream cake crowned with fresh strawberries, red carnations, and chamomiles',
    price: 'from $130',
    image: '/images/cake-strawberry-fields.jpg',
    photoCaption: 'Cake in photo shown is an 8" round',
    sizes: [
      { label: '6"', price: '$130' },
      { label: '8"', price: '$140' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'raspberry-fields',
    name: 'Raspberry Fields',
    detail: 'Classic sweet cream cake fully covered in fresh raspberries and chamomile blooms',
    note: '*Inspo from Kylie Jenner\'s birthday cake',
    price: 'from $130',
    image: '/images/cake-raspberry-fields.jpg',
    photoCaption: 'Cake in photo shown is a 10" round',
    floral: true,
    sizes: [
      { label: '6"', price: '$130' },
      { label: '8"', price: '$145' },
      { label: '10"', price: '$160' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round', 'Heart'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'spring-florals',
    name: 'Spring Florals',
    detail: 'Tall soft cream cake topped with fresh spring flowers',
    price: 'from $130',
    image: '/images/cake-spring-florals.jpg',
    photoCaption: 'Cake in photo shown is a 6" round',
    floral: true,
    otherLooksTitle: 'Other Spring Floral Looks:',
    otherLooks: [
      '/images/cake-spring-florals-1.jpg',
      '/images/cake-spring-florals-2.jpg',
    ],
    sizes: [
      { label: '6"', price: '$130' },
      { label: '8"', price: '$145' },
    ],
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'spring-anthuriums',
    name: 'Spring Anthuriums',
    detail: 'White soft cream cake topped with green anthuriums, pink tulips, and yellow blooms',
    price: 'from $130',
    image: '/images/cake-spring-anthuriums.jpg',
    photoCaption: 'Cake in photo shown is an 8" round',
    floral: true,
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'pearl-princess',
    name: 'Pearl Princess',
    detail: 'Soft cream cake with ivory orchids, garden roses, pearl accents, and scattered petals',
    price: 'from $135',
    image: '/images/cake-orchids-cream.jpg',
    photoCaption: 'Cake in photo shown is a 6" round',
    floral: true,
    sizes: [
      { label: '6"', price: '$135' },
      { label: '8"', price: '$145' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round'],
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'midnight-orchids',
    name: 'Midnight Orchids',
    detail: 'Classic sweet cream cake in black with cascading magenta orchids',
    price: 'from $135',
    image: '/images/cake-black-orchids.jpg',
    photoCaption: 'Cake in photo shown is a 6" round',
    floral: true,
    sizes: [
      { label: '6"', price: '$135' },
      { label: '8"', price: '$145' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'burgundy-figs',
    name: 'Burgundy Figs',
    detail: 'Square classic sweet cream cake with burgundy callas, white florals, figs, and grapes',
    price: 'from $140',
    image: '/images/cake-burgundy-figs.jpg',
    photoCaption: 'Cake in photo shown is an 8" square',
    floral: true,
    sizes: [
      { label: '6"', price: '$140' },
      { label: '8"', price: '$145' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round', 'Square'],
    shapesBySize: {
      '6"': ['Round'],
      '8"': ['Round', 'Square'],
    },
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'pink-lily',
    bestSeller: true,
    name: 'Pink Lily',
    detail: 'Soft cream cake topped with a pink lily and pearls in assorted sizes',
    price: 'from $130',
    image: '/images/cake-pink-lily.jpg',
    photoCaption: 'Cake in photo shown is a 6" round',
    floral: true,
    sizes: [
      { label: '6"', price: '$130' },
      { label: '8"', price: '$140' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'jellycat',
    name: 'Jellycat',
    detail: 'Cute Jellycat character cake with classic sweet cream dollops and fresh strawberries',
    price: 'from $125',
    image: '/images/cake-jellycat.jpg',
    photoCaption: 'Cake in photo shown is an 8" round',
    sizes: [
      { label: '6"', price: '$125' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Vanilla'],
    shapes: ['Round'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'sweet-cherries',
    name: 'Sweet Cherries',
    detail: 'Pink classic sweet cream cake with vintage piping and maraschino cherries',
    price: 'from $125',
    image: '/images/cake-sweet-cherries.jpg',
    photoCaption: 'Cake in photo shown is a 6" round',
    sizes: [
      { label: '6"', price: '$125' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'ily',
    name: 'ily',
    detail: 'Classic sweet cream cake with vintage piping and tiny red hearts',
    price: 'from $125',
    image: '/images/cake-ily.jpg',
    photoCaption: 'Cake in photo shown is a 6" round',
    sizes: [
      { label: '6"', price: '$125' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'vintage-love',
    name: 'Vintage Love',
    detail: 'Classic sweet cream cake with vintage piping and custom writing',
    price: 'from $125',
    image: '/images/cake-vintage-love.jpg',
    photoCaption: 'Cake in photo shown is an 8" heart',
    sizes: [
      { label: '6"', price: '$125' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'vintage-raspberry',
    name: 'Vintage Raspberry',
    detail: 'Classic sweet cream cake with vintage shell piping, topped with fresh raspberries',
    price: 'from $125',
    image: '/images/cake-vintage-raspberry.jpg',
    images: [
      '/images/cake-vintage-raspberry.jpg',
      '/images/cake-vintage-raspberry-2.jpg',
    ],
    photoCaption: 'Cake in photo shown is a 6" round',
    sizes: [
      { label: '6"', price: '$125' },
      { label: '8"', price: '$140' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'for-life',
    name: 'For Life',
    detail: 'Two-tier classic sweet cream cake with swan toppers and raspberries on the side',
    price: 'from $175',
    image: '/images/cake-for-life.jpg',
    photoCaption: 'Cake in photo shown is two-tier',
    sizes: [{ label: 'Two-tier', price: '$175' }],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'burgundy-bloom',
    name: 'Burgundy Bloom',
    detail: 'Classic sweet cream cake with spiral and topped with deep burgundy florals',
    price: 'from $130',
    image: '/images/cake-burgundy-bloom.jpg',
    photoCaption: 'Cake in photo shown is an 8" round',
    floral: true,
    sizes: [
      { label: '6"', price: '$130' },
      { label: '8"', price: '$140' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'coquette-raspberry',
    bestSeller: true,
    name: 'Coquette Raspberry',
    detail: 'Classic sweet cream off-white cake topped with raspberries, vintage piping, and white bows',
    price: 'from $125',
    image: '/images/cake-coquette-raspberry.jpg',
    images: [
      '/images/cake-coquette-raspberry.jpg',
      '/images/cake-coquette-raspberry-2.jpg',
    ],
    photoCaption: 'Cake in photo shown is an 8" round',
    sizes: [
      { label: '6"', price: '$125' },
      { label: '8"', price: '$135' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'whimsy-lily',
    bestSeller: true,
    name: 'Whimsy Lily',
    detail: 'Ruffled classic sweet cream cake with a pink lily, gems (NOT EDIBLE), and pink & white bows',
    price: 'from $135',
    image: '/images/cake-whimsy-lily.jpg',
    photoCaption: 'Cake in photo shown is an 8" round',
    floral: true,
    sizes: [
      { label: '6"', price: '$135' },
      { label: '8"', price: '$145' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round'],
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'raspberry-cupcakes',
    name: 'Raspberry Cupcakes',
    detail: 'Dozen soft cream cupcakes, each topped with a fresh raspberry',
    price: 'from $80',
    image: '/images/cake-raspberry-cupcakes.jpg',
    photoCaption: '',
    sizes: [{ label: '1 dozen (12 cupcakes)', price: '$80' }],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: [],
    fillings: [
      'Soft Cream',
      'Strawberry Soft Cream',
      'Nutella Soft Cream',
      'Chocolate Soft Cream',
      'Pistachio Soft Cream',
      'Classic Sweet Cream',
    ],
  },
  {
    slug: 'mini-cakes',
    name: 'Mini Cakes',
    detail: 'Seasonal mini cakes with fresh fruit and flowers',
    price: '$20',
    image: '/images/picnic-cakes.png',
    eventsOnly: true,
  },
  {
    slug: 'soft-cream-cake',
    name: 'Soft Cream Cake',
    detail: 'Fresh cream, light, and identical to the Asian bakery cakes (Paris Baguette).',
    price: 'from $55',
    image: '/images/cake-soft-cream.jpg',
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'floral-cake',
    name: 'Floral Cake',
    detail: 'Buttercream florals on a soft sponge base',
    price: 'from $60',
    image: '/images/cake-floral.jpg',
    floral: true,
    fillings: [
      'Soft Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'vintage-cake',
    name: 'Vintage Cake',
    detail: 'A classic sweet cream with elegant vintage piping',
    price: 'from $60',
    image: '/images/cake-vintage.jpg',
    fillings: [
      'Classic Sweet Cream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'custom-cake',
    name: 'Custom Cake',
    detail: 'DM us an inspiration photo of your dream cake and we will design it together to our best abilities <3',
    price: 'quote on request',
    image: '/images/cake-custom.jpg',
    images: [
      '/images/cake-custom.jpg',
      '/images/cake-custom-2.png',
      '/images/cake-custom-3.png',
    ],
    photoCaptions: [
      'Cake in photo shown is an 8" round',
      'Cake in photo shown is a 6" round',
      'Cake in photo shown is a 6" round',
    ],
    photoCaption: 'Cake in photo shown is an 8" round',
    sizes: [
      { label: '6"', price: '$110' },
      { label: '8"', price: '$120' },
      { label: '10"', price: '$150' },
      { label: 'Two-tier', price: '$175' },
      { label: 'Three-tier', price: 'DM/message us', note: 'Message us for three-tier pricing' },
    ],
    flavors: ['Vanilla', 'Chocolate', 'Matcha (+$10)'],
    shapes: ['Round', 'Heart', 'Dome', 'Square', 'Rectangle'],
    creams: [
      'Soft Cream',
      'Strawberry Soft Cream',
      'Nutella Soft Cream',
      'Chocolate Soft Cream',
      'Pistachio Soft Cream',
      'Classic Sweet Cream',
    ],
    fillings: [
      'Soft Cream',
      'Classic Sweet Cream',
      'Buttercream',
      'Strawberries +$5',
      'Raspberries +$5',
      'Mixed Berries (strawberries, raspberries, & blueberries) +$5',
      'Nutella +$5',
    ],
  },
  {
    slug: 'gift-card',
    name: 'Gift Card',
    detail: 'Be a sweet angel <3 — give someone an Angelle Sucre gift card for a celebration of their choosing',
    price: 'from $25',
    image: '/images/gift-card.png',
    photoCaption: '',
    giftCard: true,
    sizes: [
      { label: '$25', price: '$25' },
      { label: '$50', price: '$50' },
      { label: '$75', price: '$75' },
      { label: '$100', price: '$100' },
      { label: '$150', price: '$150' },
      { label: 'Custom amount', price: 'message us', note: 'Message us for a custom gift card amount' },
    ],
    flavors: [],
    shapes: [],
    fillings: [],
  },
]

export function getCakeBySlug(slug) {
  return cakes.find((cake) => cake.slug === slug)
}
